version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    container_name: elasticsearch
    environment:
      - cluster.name=labmeinc
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - path.repo=/snapshots
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
    volumes:
      - ./elasticsearch/es_data:/usr/share/elasticsearch/data
      - ./elasticsearch/snapshots:/snapshots
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    image: hasecuritysolutions/kibanaoss
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - esnet
  logstash:
    image: hasecuritysolutions/logstashoss
    container_name: logstash
    environment:
      - LOG_LEVEL=error
    mem_limit: 2g
    ports:
      - 5044:5044
      - 5045:5045
      - 6050:6050
    volumes:
      - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash/logstash_configs:/opt/logstash_configs:ro
      - ./logstash/rules:/etc/nsm/rules:ro
      - ./logstash/persistent_data:/usr/share/logstash/data
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - esnet
  freq_server:
    image: hasecuritysolutions/freq_server
    container_name: freq_server
    ports:
      - 10004:10004
    networks:
      - esnet
  domain_stats:
    image: hasecuritysolutions/domain_stats
    container_name: domain_stats
    ports:
      - 20000:20000
    networks:
      - esnet
  cerebro:
    image: dylanmei/cerebro
    container_name: cerebro
    depends_on:
      - elasticsearch
    ports:
      - 9000:9000
    networks:
      - esnet
  elastic_cron:
    image: hasecuritysolutions/elastic_cron
    container_name: elastic_cron
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./cron/elastic-cron:/var/spool/cron/crontabs/elastic-cron:ro
      - ./curator:/etc/curator:ro
    networks:
      - esnet
  elastalert:
    image: hasecuritysolutions/elastalert
    container_name: elastalert
    depends_on:
      - elasticsearch
    volumes:
      - ./elastalert:/etc/elastalert:ro
    networks:
      - esnet

networks:
  esnet:
    driver: bridge