version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: elasticsearch
    environment:
      - cluster.name=labmeinc
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 8g
    volumes:
      - es1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.2
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - esnet
  logstash:
    image: lightforge/logstashwithcommunityplugins
    container_name: logstash
    environment:
      - LOG_LEVEL=error
    ports:
      - 5044:5044
      - 5045:5045
      - 6050:6050
    volumes:
      - /opt/Logstash-Pipelines/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - /opt/Logstash-Pipelines:/opt/Logstash-Pipelines:ro
      - /etc/nsm/rules:/etc/nsm/rules:ro
      - ls1:/usr/share/logstash/data
    environment:
      LS_JAVA_OPTS: "-Xmx2g -Xms2g"
    networks:
      - esnet
  freq_server:
    image: lightforge/freq_server
    container_name: freq_server
    ports:
      - 10004:10004
    networks:
      - esnet
  domain_stats:
    image: lightforge/domain_stats
    container_name: domain_stats
    ports:
      - 20000:20000
    networks:
      - esnet
  cerebro:
    image: dylanmei/cerebro
    container_name: cerebro
    depends_on:
      - elasticsearch
    ports:
      - 9000:9000
    networks:
      - esnet

volumes:
  es1:
    driver: local
  ls1:
    driver: local

networks:
  esnet:
    driver: bridge